=== EchoThreeLLC/echothree/ui/cli/database/src/xml/DatabaseDefinition.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--                                                                                  -->
<!-- Copyright 2002-2021 Echo Three, LLC                                              -->
<!--                                                                                  -->
<!-- Licensed under the Apache License, Version 2.0 (the "License");                  -->
<!-- you may not use this file except in compliance with the License.                 -->
<!-- You may obtain a copy of the License at                                          -->
<!--                                                                                  -->
<!--     http://www.apache.org/licenses/LICENSE-2.0                                   -->
<!--                                                                                  -->
<!-- Unless required by applicable law or agreed to in writing, software              -->
<!-- distributed under the License is distributed on an "AS IS" BASIS,                -->
<!-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.         -->
<!-- See the License for the specific language governing permissions and              -->
<!-- limitations under the License.                                                   -->
<!--                                                                                  -->
<!ELEMENT column EMPTY>
<!ATTLIST column
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    maxLength CDATA #IMPLIED
    nullAllowed (false | true) #IMPLIED
    description CDATA #IMPLIED
    onParentDelete CDATA #IMPLIED
    destinationTable CDATA #IMPLIED
    destinationColumn CDATA #IMPLIED>
<!ELEMENT indexColumn EMPTY>
<!ATTLIST indexColumn
    name CDATA #REQUIRED>
<!ELEMENT columnType EMPTY>
<!ATTLIST columnType
    type CDATA #REQUIRED
    realType (Boolean | String | Date | Integer | Long | Time ) #REQUIRED
    maxLength CDATA #IMPLIED
    onParentDelete CDATA #IMPLIED
    destinationTable CDATA #IMPLIED
    destinationColumn CDATA #IMPLIED>
<!ELEMENT columnTypes (columnType+)>
<!ELEMENT file EMPTY>
<!ATTLIST file
    name CDATA #REQUIRED>
<!ELEMENT files (file+)>
<!ELEMENT columns (column+)>
<!ELEMENT database (columnTypes?, files?, components?)>
<!ATTLIST database
    name CDATA #REQUIRED>
<!ELEMENT fetchColumn EMPTY>
<!ATTLIST fetchColumn
    name CDATA #REQUIRED>
<!ELEMENT index (indexColumn+)>
<!ATTLIST index
    type (Multiple | PrimaryKey | Unique) #REQUIRED
    name CDATA #IMPLIED>
<!ELEMENT indexes (index*)>
<!ELEMENT reference EMPTY>
<!ATTLIST reference
    sourceColumn CDATA #REQUIRED>
<!ELEMENT table (columns?, indexes?)>
<!ATTLIST table
    namePlural CDATA #REQUIRED
    nameSingular CDATA #REQUIRED
    columnPrefix CDATA #REQUIRED
    chunkSize CDATA #IMPLIED
    description CDATA #IMPLIED>
<!ELEMENT tables (table*)>
<!ELEMENT component (tables?)>
<!ATTLIST component
    name CDATA #REQUIRED>
<!ELEMENT components (component*)>

=== EchoThreeLLC/echothree/ui/cli/database/src/xml/JobComponent.xml
<?xml version="1.0"?>
<!DOCTYPE database SYSTEM "DatabaseDefinition.dtd">
<!--                                                                                  -->
<!-- Copyright 2002-2019 Echo Three, LLC                                              -->
<!--                                                                                  -->
<!-- Licensed under the Apache License, Version 2.0 (the "License");                  -->
<!-- you may not use this file except in compliance with the License.                 -->
<!-- You may obtain a copy of the License at                                          -->
<!--                                                                                  -->
<!--     http://www.apache.org/licenses/LICENSE-2.0                                   -->
<!--                                                                                  -->
<!-- Unless required by applicable law or agreed to in writing, software              -->
<!-- distributed under the License is distributed on an "AS IS" BASIS,                -->
<!-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.         -->
<!-- See the License for the specific language governing permissions and              -->
<!-- limitations under the License.                                                   -->
<!--                                                                                  -->
<database name="echothree">
    <components>
        <component name="Job">
            <tables>
                <table namePlural="Jobs" nameSingular="Job" columnPrefix="jb">
                    <columns>
                        <column name="JobId" type="EID" nullAllowed="false" />
                        <column name="ActiveDetailId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="JobDetails" destinationColumn="JobDetailId"/>
                        <column name="LastDetailId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="JobDetails" destinationColumn="JobDetailId"/>
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="JobId" />
                        </index>
                        <index type="Unique">
                            <indexColumn name="ActiveDetailId" />
                        </index>
                        <index type="Unique">
                            <indexColumn name="LastDetailId" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="JobDetails" nameSingular="JobDetail" columnPrefix="jbdt">
                    <columns>
                        <column name="JobDetailId" type="EID" nullAllowed="false" />
                        <column name="JobId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Jobs" destinationColumn="JobId" />
                        <column name="JobName" type="Name" nullAllowed="false" />
                        <column name="RunAsPartyId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Parties" destinationColumn="PartyId" />
                        <column name="SortOrder" type="Integer" nullAllowed="false" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="JobDetailId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="JobId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Unique" name="Index2">
                            <indexColumn name="JobName" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index3">
                            <indexColumn name="RunAsPartyId" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="JobDescriptions" nameSingular="JobDescription" columnPrefix="jbd">
                    <columns>
                        <column name="JobDescriptionId" type="EID" nullAllowed="false" />
                        <column name="JobId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Jobs" destinationColumn="JobId" />
                        <column name="LanguageId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Languages" destinationColumn="LanguageId" />
                        <column name="Description" type="Description" nullAllowed="false" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="JobDescriptionId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="JobId" />
                            <indexColumn name="LanguageId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index2">
                            <indexColumn name="LanguageId" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="JobStatuses" nameSingular="JobStatus" columnPrefix="jbst">
                    <columns>
                        <column name="JobStatusId" type="EID" nullAllowed="false" />
                        <column name="JobId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Jobs" destinationColumn="JobId"/>
                        <column name="LastStartTime" type="Time" nullAllowed="true" />
                        <column name="LastEndTime" type="Time" nullAllowed="true" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="JobStatusId" />
                        </index>
                        <index type="Unique">
                            <indexColumn name="JobId" />
                        </index>
                    </indexes>
                </table>
            </tables>
        </component>
    </components>
</database>

=== EchoThreeLLC/echothree/ui/cli/database/src/xml/TrackComponent.xml
<?xml version="1.0"?>
<!DOCTYPE database SYSTEM "DatabaseDefinition.dtd">
<!--                                                                                  -->
<!-- Copyright 2002-2022 Echo Three, LLC                                              -->
<!--                                                                                  -->
<!-- Licensed under the Apache License, Version 2.0 (the "License");                  -->
<!-- you may not use this file except in compliance with the License.                 -->
<!-- You may obtain a copy of the License at                                          -->
<!--                                                                                  -->
<!--     http://www.apache.org/licenses/LICENSE-2.0                                   -->
<!--                                                                                  -->
<!-- Unless required by applicable law or agreed to in writing, software              -->
<!-- distributed under the License is distributed on an "AS IS" BASIS,                -->
<!-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.         -->
<!-- See the License for the specific language governing permissions and              -->
<!-- limitations under the License.                                                   -->
<!--                                                                                  -->
<database name="echothree">
    <components>
        <component name="Track">
            <tables>
                <table namePlural="Tracks" nameSingular="Track" columnPrefix="trk">
                    <columns>
                        <column name="TrackId" type="EID" nullAllowed="false" />
                        <column name="ActiveDetailId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="TrackDetails" destinationColumn="TrackDetailId"/>
                        <column name="LastDetailId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="TrackDetails" destinationColumn="TrackDetailId"/>
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="TrackId" />
                        </index>
                        <index type="Unique">
                            <indexColumn name="ActiveDetailId"/>
                        </index>
                        <index type="Unique">
                            <indexColumn name="LastDetailId"/>
                        </index>
                    </indexes>
                </table>
                <table namePlural="TrackDetails" nameSingular="TrackDetail" columnPrefix="trkdt">
                    <columns>
                        <column name="TrackDetailId" type="EID" nullAllowed="false" />
                        <column name="TrackId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Tracks" destinationColumn="TrackId" />
                        <column name="TrackName" type="Name" nullAllowed="false" />
                        <column name="ValueSha1Hash" type="Sha1Hash" nullAllowed="false" />
                        <column name="Value" type="CLOB" nullAllowed="false" />                        
                        <column name="IsDefault" type="Boolean" nullAllowed="false" />
                        <column name="SortOrder" type="Integer" nullAllowed="false" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="TrackDetailId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="TrackId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Unique" name="Index2">
                            <indexColumn name="TrackName" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Unique" name="Index3">
                            <indexColumn name="ValueSha1Hash" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index4">
                            <indexColumn name="IsDefault" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="TrackDescriptions" nameSingular="TrackDescription" columnPrefix="trkd">
                    <columns>
                        <column name="TrackDescriptionId" type="EID" nullAllowed="false" />
                        <column name="TrackId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Tracks" destinationColumn="TrackId" />
                        <column name="LanguageId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Languages" destinationColumn="LanguageId" />
                        <column name="Description" type="Description" nullAllowed="false" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="TrackDescriptionId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="TrackId" />
                            <indexColumn name="LanguageId" />
                            <indexColumn name="ThruTime"/>
                        </index>
                        <index type="Multiple" name="Index2">
                            <indexColumn name="TrackId" />
                            <indexColumn name="ThruTime"/>
                        </index>
                        <index type="Multiple" name="Index3">
                            <indexColumn name="LanguageId" />
                            <indexColumn name="ThruTime"/>
                        </index>
                    </indexes>
                </table>
                <table namePlural="UserVisitTracks" nameSingular="UserVisitTrack" columnPrefix="uvistrk">
                    <columns>
                        <column name="UserVisitTrackId" type="EID" nullAllowed="false" />
                        <column name="UserVisitId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="UserVisits" destinationColumn="UserVisitId" />
                        <column name="UserVisitTrackSequence" type="Integer" nullAllowed="false" />
                        <column name="Time" type="Time" nullAllowed="false" />
                        <column name="TrackId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="Tracks" destinationColumn="TrackId" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="UserVisitTrackId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="UserVisitId" />
                            <indexColumn name="UserVisitTrackSequence" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index2">
                            <indexColumn name="TrackId" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
            </tables>
        </component>
    </components>
</database>
