=== EchoThreeLLC/echothree/ui/cli/database/src/xml/DatabaseDefinition.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--                                                                                  -->
<!-- Copyright 2002-2021 Echo Three, LLC                                              -->
<!--                                                                                  -->
<!-- Licensed under the Apache License, Version 2.0 (the "License");                  -->
<!-- you may not use this file except in compliance with the License.                 -->
<!-- You may obtain a copy of the License at                                          -->
<!--                                                                                  -->
<!--     http://www.apache.org/licenses/LICENSE-2.0                                   -->
<!--                                                                                  -->
<!-- Unless required by applicable law or agreed to in writing, software              -->
<!-- distributed under the License is distributed on an "AS IS" BASIS,                -->
<!-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.         -->
<!-- See the License for the specific language governing permissions and              -->
<!-- limitations under the License.                                                   -->
<!--                                                                                  -->
<!ELEMENT column EMPTY>
<!ATTLIST column
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    maxLength CDATA #IMPLIED
    nullAllowed (false | true) #IMPLIED
    description CDATA #IMPLIED
    onParentDelete CDATA #IMPLIED
    destinationTable CDATA #IMPLIED
    destinationColumn CDATA #IMPLIED>
<!ELEMENT indexColumn EMPTY>
<!ATTLIST indexColumn
    name CDATA #REQUIRED>
<!ELEMENT columnType EMPTY>
<!ATTLIST columnType
    type CDATA #REQUIRED
    realType (Boolean | String | Date | Integer | Long | Time ) #REQUIRED
    maxLength CDATA #IMPLIED
    onParentDelete CDATA #IMPLIED
    destinationTable CDATA #IMPLIED
    destinationColumn CDATA #IMPLIED>
<!ELEMENT columnTypes (columnType+)>
<!ELEMENT file EMPTY>
<!ATTLIST file
    name CDATA #REQUIRED>
<!ELEMENT files (file+)>
<!ELEMENT columns (column+)>
<!ELEMENT database (columnTypes?, files?, components?)>
<!ATTLIST database
    name CDATA #REQUIRED>
<!ELEMENT fetchColumn EMPTY>
<!ATTLIST fetchColumn
    name CDATA #REQUIRED>
<!ELEMENT index (indexColumn+)>
<!ATTLIST index
    type (Multiple | PrimaryKey | Unique) #REQUIRED
    name CDATA #IMPLIED>
<!ELEMENT indexes (index*)>
<!ELEMENT reference EMPTY>
<!ATTLIST reference
    sourceColumn CDATA #REQUIRED>
<!ELEMENT table (columns?, indexes?)>
<!ATTLIST table
    namePlural CDATA #REQUIRED
    nameSingular CDATA #REQUIRED
    columnPrefix CDATA #REQUIRED
    chunkSize CDATA #IMPLIED
    description CDATA #IMPLIED>
<!ELEMENT tables (table*)>
<!ELEMENT component (tables?)>
<!ATTLIST component
    name CDATA #REQUIRED>
<!ELEMENT components (component*)>

=== EchoThreeLLC/echothree/ui/cli/database/src/xml/StyleComponent.xml
<?xml version="1.0"?>
<!DOCTYPE database SYSTEM "DatabaseDefinition.dtd">
<!--                                                                                  -->
<!-- Copyright 2002-2018 Echo Three, LLC                                              -->
<!--                                                                                  -->
<!-- Licensed under the Apache License, Version 2.0 (the "License");                  -->
<!-- you may not use this file except in compliance with the License.                 -->
<!-- You may obtain a copy of the License at                                          -->
<!--                                                                                  -->
<!--     http://www.apache.org/licenses/LICENSE-2.0                                   -->
<!--                                                                                  -->
<!-- Unless required by applicable law or agreed to in writing, software              -->
<!-- distributed under the License is distributed on an "AS IS" BASIS,                -->
<!-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.         -->
<!-- See the License for the specific language governing permissions and              -->
<!-- limitations under the License.                                                   -->
<!--                                                                                  -->
<database name="echothree">
    <components>
        <component name="Style">
            <tables>
                <table namePlural="StylePaths" nameSingular="StylePath" columnPrefix="stylpth">
                    <columns>
                        <column name="StylePathId" type="EID" nullAllowed="false" />
                        <column name="ActiveDetailId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="StylePathDetails" destinationColumn="StylePathDetailId"/>
                        <column name="LastDetailId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="StylePathDetails" destinationColumn="StylePathDetailId"/>
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="StylePathId" />
                        </index>
                        <index type="Unique">
                            <indexColumn name="ActiveDetailId" />
                        </index>
                        <index type="Unique">
                            <indexColumn name="LastDetailId" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="StylePathDetails" nameSingular="StylePathDetail" columnPrefix="stylpthdt">
                    <columns>
                        <column name="StylePathDetailId" type="EID" nullAllowed="false" />
                        <column name="StylePathId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="StylePaths" destinationColumn="StylePathId" />
                        <column name="StylePathName" type="Name" nullAllowed="false" />
                        <column name="IsDefault" type="Boolean" nullAllowed="false" />
                        <column name="SortOrder" type="Integer" nullAllowed="false" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="StylePathDetailId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="StylePathId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Unique" name="Index2">
                            <indexColumn name="StylePathName" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index3">
                            <indexColumn name="IsDefault" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="StylePathDescriptions" nameSingular="StylePathDescription" columnPrefix="stylpthd">
                    <columns>
                        <column name="StylePathDescriptionId" type="EID" nullAllowed="false" />
                        <column name="StylePathId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="StylePaths" destinationColumn="StylePathId" />
                        <column name="LanguageId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Languages" destinationColumn="LanguageId" />
                        <column name="Description" type="Description" nullAllowed="false" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="StylePathDescriptionId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="StylePathId" />
                            <indexColumn name="LanguageId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index2">
                            <indexColumn name="LanguageId" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
            </tables>
        </component>
    </components>
</database>

=== EchoThreeLLC/echothree/ui/cli/database/src/xml/SalesComponent.xml
<?xml version="1.0"?>
<!DOCTYPE database SYSTEM "DatabaseDefinition.dtd">
<!--                                                                                  -->
<!-- Copyright 2002-2022 Echo Three, LLC                                              -->
<!--                                                                                  -->
<!-- Licensed under the Apache License, Version 2.0 (the "License");                  -->
<!-- you may not use this file except in compliance with the License.                 -->
<!-- You may obtain a copy of the License at                                          -->
<!--                                                                                  -->
<!--     http://www.apache.org/licenses/LICENSE-2.0                                   -->
<!--                                                                                  -->
<!-- Unless required by applicable law or agreed to in writing, software              -->
<!-- distributed under the License is distributed on an "AS IS" BASIS,                -->
<!-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.         -->
<!-- See the License for the specific language governing permissions and              -->
<!-- limitations under the License.                                                   -->
<!--                                                                                  -->
<database name="echothree">
    <components>
        <component name="Sales">
            <tables>
                <table namePlural="SalesOrderBatches" nameSingular="SalesOrderBatch" columnPrefix="salordbtch">
                    <columns>
                        <column name="SalesOrderBatchId" type="EID" nullAllowed="false" />
                        <column name="BatchId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Batches" destinationColumn="BatchId" />
                        <column name="PaymentMethodId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="PaymentMethods" destinationColumn="PaymentMethodId" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="SalesOrderBatchId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="BatchId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index2">
                            <indexColumn name="PaymentMethodId" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="SalesOrders" nameSingular="SalesOrder" columnPrefix="salord">
                    <columns>
                        <column name="SalesOrderId" type="EID" nullAllowed="false" />
                        <column name="OrderId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Orders" destinationColumn="OrderId" />
                        <column name="OfferUseId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="OfferUses" destinationColumn="OfferUseId" />
                        <column name="AssociateReferralId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="AssociateReferrals" destinationColumn="AssociateReferralId" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="SalesOrderId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="OrderId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index2">
                            <indexColumn name="OfferUseId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index3">
                            <indexColumn name="AssociateReferralId" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="SalesOrderLines" nameSingular="SalesOrderLine" columnPrefix="salordl">
                    <columns>
                        <column name="SalesOrderLineId" type="EID" nullAllowed="false" />
                        <column name="OrderLineId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="OrderLines" destinationColumn="OrderLineId" />
                        <column name="OfferUseId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="OfferUses" destinationColumn="OfferUseId" />
                        <column name="AssociateReferralId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="AssociateReferrals" destinationColumn="AssociateReferralId" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="SalesOrderLineId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="OrderLineId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index2">
                            <indexColumn name="OfferUseId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index3">
                            <indexColumn name="AssociateReferralId" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
            </tables>
        </component>
    </components>
</database>

=== EchoThreeLLC/echothree/ui/cli/database/src/xml/ShippingComponent.xml
<?xml version="1.0"?>
<!DOCTYPE database SYSTEM "DatabaseDefinition.dtd">
<!--                                                                                  -->
<!-- Copyright 2002-2025 Echo Three, LLC                                              -->
<!--                                                                                  -->
<!-- Licensed under the Apache License, Version 2.0 (the "License");                  -->
<!-- you may not use this file except in compliance with the License.                 -->
<!-- You may obtain a copy of the License at                                          -->
<!--                                                                                  -->
<!--     http://www.apache.org/licenses/LICENSE-2.0                                   -->
<!--                                                                                  -->
<!-- Unless required by applicable law or agreed to in writing, software              -->
<!-- distributed under the License is distributed on an "AS IS" BASIS,                -->
<!-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.         -->
<!-- See the License for the specific language governing permissions and              -->
<!-- limitations under the License.                                                   -->
<!--                                                                                  -->
<database name="echothree">
    <components>
        <component name="Shipping">
            <tables>
                <table namePlural="ShippingMethods" nameSingular="ShippingMethod" columnPrefix="shm">
                    <columns>
                        <column name="ShippingMethodId" type="EID" nullAllowed="false" />
                        <column name="ActiveDetailId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="ShippingMethodDetails" destinationColumn="ShippingMethodDetailId"/>
                        <column name="LastDetailId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="ShippingMethodDetails" destinationColumn="ShippingMethodDetailId"/>
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="ShippingMethodId" />
                        </index>
                        <index type="Unique">
                            <indexColumn name="ActiveDetailId" />
                        </index>
                        <index type="Unique">
                            <indexColumn name="LastDetailId" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="ShippingMethodDetails" nameSingular="ShippingMethodDetail" columnPrefix="shmdt">
                    <columns>
                        <column name="ShippingMethodDetailId" type="EID" nullAllowed="false" />
                        <column name="ShippingMethodId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="ShippingMethods" destinationColumn="ShippingMethodId" />
                        <column name="ShippingMethodName" type="Name" nullAllowed="false" />
                        <column name="GeoCodeSelectorId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="Selectors" destinationColumn="SelectorId" />
                        <column name="ItemSelectorId" type="ForeignKey" nullAllowed="true" onParentDelete="delete" destinationTable="Selectors" destinationColumn="SelectorId" />
                        <column name="SortOrder" type="Integer" nullAllowed="false" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="ShippingMethodDetailId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="ShippingMethodId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Unique" name="Index2">
                            <indexColumn name="ShippingMethodName" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index3">
                            <indexColumn name="GeoCodeSelectorId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index4">
                            <indexColumn name="ItemSelectorId" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="ShippingMethodDescriptions" nameSingular="ShippingMethodDescription" columnPrefix="shmd">
                    <columns>
                        <column name="ShippingMethodDescriptionId" type="EID" nullAllowed="false" />
                        <column name="ShippingMethodId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="ShippingMethods" destinationColumn="ShippingMethodId" />
                        <column name="LanguageId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="Languages" destinationColumn="LanguageId" />
                        <column name="Description" type="Description" nullAllowed="false" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="ShippingMethodDescriptionId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="ShippingMethodId" />
                            <indexColumn name="LanguageId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index2">
                            <indexColumn name="LanguageId" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
                <table namePlural="ShippingMethodCarrierServices" nameSingular="ShippingMethodCarrierService" columnPrefix="shmcrrsrv">
                    <columns>
                        <column name="ShippingMethodCarrierServiceId" type="EID" nullAllowed="false" />
                        <column name="ShippingMethodId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="ShippingMethods" destinationColumn="ShippingMethodId" />
                        <column name="CarrierServiceId" type="ForeignKey" nullAllowed="false" onParentDelete="delete" destinationTable="CarrierServices" destinationColumn="CarrierServiceId" />
                        <column name="FromTime" type="Time" nullAllowed="false" />
                        <column name="ThruTime" type="Time" nullAllowed="false" />
                    </columns>
                    <indexes>
                        <index type="PrimaryKey">
                            <indexColumn name="ShippingMethodCarrierServiceId" />
                        </index>
                        <index type="Unique" name="Index1">
                            <indexColumn name="ShippingMethodId" />
                            <indexColumn name="CarrierServiceId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index2">
                            <indexColumn name="ShippingMethodId" />
                            <indexColumn name="ThruTime" />
                        </index>
                        <index type="Multiple" name="Index3">
                            <indexColumn name="CarrierServiceId" />
                            <indexColumn name="ThruTime" />
                        </index>
                    </indexes>
                </table>
            </tables>
        </component>
    </components>
</database>
